HISTORY.rst, flake8_comprehensions.py, tests/test_it.py
=> Fix crash on method calls

HISTORY.rst, README.rst, flake8_comprehensions.py, tests/test_it.py
=> Split all rule codes by type

HISTORY.rst, flake8_comprehensions.py, tests/test_it.py
=> C407 - unnecessary list comprehension - 'x' can take a generator

HISTORY.rst, flake8_comprehensions.py, tests/test_it.py
=> Fix C402 false positive where a function call is involved

.travis.yml
https://docs.travis-ci.com/user/caching/#pip-cache
=> Add pip caching to Travis CI

README.rst, flake8_comprehensions.py, tests/test_it.py
* Change wording to be less repetitive
* Add docs in README
=> C408 tweaks

HISTORY.rst, flake8_comprehensions.py, tests/test_it.py
=> Fix false positives in C408 for calls using *args or **kwargs

README.rst
=> Reword documentation to be easier for non-native English speakers

HISTORY.rst, README.rst, flake8_comprehensions.py, test_flake8_comprehensions.py
Fixes #61. Thanks @pope1ni for the original PR in #108.
=> Added missing builtin enumerate to C407

flake8_comprehensions.py
As a Python 3 only project, all classes are "new style" classes by default. This instance was detected by running pyupgrade.
https://github.com/asottile/pyupgrade
=> Remove unnecessary base object

HISTORY.rst, src/flake8_comprehensions.py, tests/test_flake8_comprehensions.py
=> Fix C407 to catch cases where enumerate and sum have >1 argument

tests/test_flake8_comprehensions.py
Use pytest-flake8dir to deduplicate the work of running flake8 and don't search for a regex
=> Tidy version test

HISTORY.rst, src/flake8_comprehensions.py, tests/test_flake8_comprehensions.py
=> Fix false positives in c416 for asynchronous comprehensions

HISTORY.rst, src/flake8_comprehensions.py, tests/test_flake8_comprehensions.py
=> Fix false positives in C416 for list comprehensions returning tuples

HISTORY.rst, src/flake8_comprehensions.py, tests/test_flake8_comprehensions.py
=> Fix C416 async false positive on Python 3.6 too

HISTORY.rst, README.rst, src/flake8_comprehensions.py, tests/test_flake8_comprehensions.py
=> Check for dict and set comprehensions in rules C407 and C412

tests/test_flake8_comprehensions.py
In case of wrapping as in https://github.com/adamchainz/flake8-tidy-imports/pull/205
=> Improve version test

HISTORY.rst, README.rst, src/flake8_comprehensions.py, tests/test_flake8_comprehensions.py
Ref #249 where a user said they missed it.
=> Restore C408 checking for dict with keyword-only arguments

src/flake8_comprehensions.py, tests/test_flake8_comprehensions.py, tox.ini
=> Drop more Python 3.5 references

HISTORY.rst, src/flake8_comprehensions/__init__.py
=> Fix type for tree argument

pyproject.toml, requirements/compile.py, setup.py, src/flake8_comprehensions/__init__.py, tests/test_flake8_comprehensions.py
=> Add __future__.annotations to all files

HISTORY.rst, src/flake8_comprehensions/__init__.py, tests/test_flake8_comprehensions.py
=> Fix C402/C404 false positive for dict() with kwargs

CHANGELOG.rst, src/flake8_comprehensions/__init__.py, tests/test_flake8_comprehensions.py
=> Fix C406 false positives

CHANGELOG.rst, README.rst, src/flake8_comprehensions/__init__.py, tests/test_flake8_comprehensions.py
Fixes #499. Needed a new rule actually.
=> Add rule for unnecessary dict() calls
